# Generated by Django 4.1.3 on 2023-02-08 11:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_title', models.CharField(max_length=150)),
                ('publishing_year', models.IntegerField()),
                ('author', models.CharField(max_length=100)),
                ('plot', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Institution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('institution_name', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'institution',
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('problem_id', models.IntegerField(primary_key=True, serialize=False)),
                ('problem_name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('usertype', models.CharField(max_length=2)),
            ],
            options={
                'db_table': 'problem_details',
            },
        ),
        migrations.CreateModel(
            name='Solution_details',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solution_upload', models.FileField(upload_to=main.models.user_directory_path_solution_details, validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['pdf'])])),
                ('problem_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.problem')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'solution_details',
            },
        ),
        migrations.CreateModel(
            name='Mentordetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phoneno', models.CharField(max_length=15)),
                ('institution_name', models.CharField(max_length=100)),
                ('designation', models.CharField(max_length=100)),
                ('upload_photo', models.ImageField(upload_to=main.models.user_directory_path_mentor)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'mentor_details',
            },
        ),
        migrations.CreateModel(
            name='Memberdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phoneno', models.CharField(max_length=15)),
                ('institution_name', models.CharField(max_length=100)),
                ('upload_photo', models.ImageField(upload_to=main.models.user_directory_path_member_photo)),
                ('institution_id', models.ImageField(upload_to=main.models.user_directory_path_member_idcard)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'member_details',
            },
        ),
        migrations.CreateModel(
            name='MainParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teamleadname', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=15)),
                ('institution_name', models.CharField(max_length=50)),
                ('institution_address', models.CharField(max_length=500)),
                ('upload_photo', models.ImageField(upload_to=main.models.user_directory_path_main_participant_photo)),
                ('college_id', models.ImageField(upload_to=main.models.user_directory_path_main_participant_idcard)),
                ('status', models.CharField(max_length=1)),
                ('usertype', models.CharField(max_length=2)),
                ('remark', models.CharField(max_length=100, null=True)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'main_participant',
            },
        ),
    ]
