# Generated by Django 4.1.3 on 2023-01-06 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='institution',
            old_name='Institution_name',
            new_name='institution_name',
        ),
    ]
