# Generated by Django 4.1.3 on 2023-01-06 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_rename_institution_name_institution_institution_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainparticipant',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='mainparticipant',
            name='modified_on',
        ),
    ]
