# Generated by Django 4.1.3 on 2023-01-10 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_problem_solution_details_delete_idcard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mentordetails',
            old_name='organization',
            new_name='designation',
        ),
        migrations.AddField(
            model_name='mentordetails',
            name='institution_name',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
