# Generated by Django 4.1.3 on 2023-01-10 16:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import main.models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0006_rename_organization_mentordetails_designation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Memberdetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('phoneno', models.CharField(max_length=15)),
                ('institution_name', models.CharField(max_length=100)),
                ('institution_id', models.FileField(upload_to=main.models.user_directory_path)),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'member_details',
            },
        ),
    ]
