# Generated by Django 4.1.3 on 2023-01-11 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_remove_problem_id_problem_problem_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainparticipant',
            name='problem_statement_id',
        ),
        migrations.RemoveField(
            model_name='mainparticipant',
            name='solution_id',
        ),
    ]
