# Generated by Django 4.1.3 on 2023-01-11 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_remove_mainparticipant_problem_statement_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainparticipant',
            name='institution_id',
        ),
        migrations.AddField(
            model_name='mainparticipant',
            name='institution_address',
            field=models.CharField(default=1, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mainparticipant',
            name='institution_name',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
