# Generated by Django 4.1.3 on 2023-01-12 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_alter_problem_description_alter_problem_problem_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solution',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='ProblemStatment',
        ),
        migrations.DeleteModel(
            name='Solution',
        ),
    ]
