# Generated by Django 4.1.3 on 2023-01-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_solution_user_id_delete_problemstatment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainparticipant',
            name='status',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
